apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php
        image: php:8.0-fpm  # Use the desired PHP version
        ports:
        - containerPort: 9000
        env:
        - name: DB_HOST
          value: "demopostgres"  # Service name of PostgreSQL
        - name: DB_USER
          value: "demo2"      # PostgreSQL user
        - name: DB_PASSWORD
          value: "demo2"  # PostgreSQL password
        - name: DB_NAME
          value: "demo2db"    # PostgreSQL database name
        volumeMounts:
        - name: php-storage
          mountPath: /var/www/html/my-php-app
        - name: php-config
          mountPath: /var/www/html/my-php-app/index.php
          subPath: index.php
      volumes:
      - name: php-storage
        persistentVolumeClaim:
          claimName: php-pvc  # Reference to a PVC for the PHP application
      - name: php-config
        configMap:
          name: php-app-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed

---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort  # Change the service type to NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000  # Optional: Specify a custom NodePort, or let Kubernetes assign one
  selector:
    app: php-app
