apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php
        image: php:8.0-fpm  # Use the desired PHP version
        ports:
        - containerPort: 9000
        env:
        - name: DB_HOST
          value: "apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13  # Specify the desired version of PostgreSQL
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "demo2"  # Replace with your desired username
        - name: POSTGRES_PASSWORD
          value: "demo2"  # Replace with your desired password
        - name: POSTGRES_DB
          value: "demo2db"  # Replace with your desired database name
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data  # Default data directory
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc  # Reference to the PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed"  # Service name of PostgreSQL
        - name: DB_USER
          value: "user"      # PostgreSQL user
        - name: DB_PASSWORD
          value: "password"  # PostgreSQL password
        - name: DB_NAME
          value: "dbname"    # PostgreSQL database name
        volumeMounts:
        - name: php-storage
          mountPath: /var/www/html/my-php-app
      volumes:
      - name: php-storage
        persistentVolumeClaim:
          claimName: php-pvc  # Reference to a PVC for the PHP application
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort  # Change the service type to NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000  # Optional: Specify a custom NodePort, or let Kubernetes assign one
  selector:
    app: php-app
